apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: mapit-deploy-pipeline
spec:
  resources:
  - name: samples-git
    type: git
  - name: voting-vote-image
    type: image
  - name: voting-worker-image
    type: image
  - name: voting-result-image
    type: image
  tasks:
  - name: build-worker
    taskRef:
      name: mvn-build
    params:
    - name: folder
      value: /workspace/vote/worker/
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
      outputs:
      - name: workspace-git
        resource: samples-git
  - name: test-worker
    taskRef:
      name: mvn-test
    params:
    - name: folder
      value: /workspace/vote/worker/
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
        from: [build-worker]
  - name: analyse-code-worker
    taskRef:
      name: static-analysis
    params:
    - name: folder
      value: /workspace/vote/worker/
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
        from: [build-worker]
  - name: build-worker-image
    taskRef:
      name: buildah
    params:
    - name: dockerfile
      value: Dockerfile
    - name: contextFolder
      value: ./vote/worker/
    - name: verifyTLS
      value: "false"
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
        from: [build-worker]
      outputs:
      - name: image
        resource: voting-worker-image
    runAfter:
      - analyse-code-worker
      - test-worker
  - name: build-vote-image
    taskRef:
      name: buildah
    params:
    - name: contextFolder
      value: ./vote/vote/
    - name: verifyTLS
      value: "false"
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
      outputs:
      - name: image
        resource: voting-vote-image
  - name: build-result-image
    taskRef:
      name: buildah
    params:
    - name: contextFolder
      value: ./vote/result/
    - name: verifyTLS
      value: "false"
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
      outputs:
      - name: image
        resource: voting-result-image
  - name: deploy-worker
    taskRef:
      name: openshift-cli-rollout
    params:
    - name: app
      value: voting-worker
    runAfter:
      - build-worker-image
  - name: deploy-vote
    taskRef:
      name: openshift-cli-rollout
    params:
    - name: app
      value: voting-vote
    runAfter:
      - build-vote-image
  - name: deploy-result
    taskRef:
      name: openshift-cli-rollout
    params:
    - name: app
      value: voting-result
    runAfter:
      - build-result-image
