---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: samples-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/vdemeester/openshift-pipelines-samples.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: voting-worker-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-demo/voting-worker
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: voting-vote-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-demo/voting-vote
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: voting-result-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-demo/voting-result
