apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voting-api
  name: voting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-api
  template:
    metadata:
      labels:
        app: voting-api
    spec:
      containers:
        - image: quay.io/sthaha/voting-api:latest
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 9000
              protocol: TCP
