apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ""
      apiVersion: "1.0"
      kind: DockerImage
    dockerImageMetadataVersion: "1.0"
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/imported-from: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:10
    creationTimestamp: null
    labels:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: voting
      app.kubernetes.io/version: "1.0"
    name: postgresql:10
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:10
    generation: null
    importPolicy: {}
    name: "10"
    referencePolicy:
      type: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      app.openshift.io/connects-to: '["voting-worker","voting-result"]'
    creationTimestamp: null
    labels:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: voting
      app.kubernetes.io/version: "1.0"
    name: postgresql
  spec:
    replicas: 1
    selector:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: voting
      app.kubernetes.io/version: "1.0"
      deploymentconfig: postgresql
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
          app.openshift.io/connects-to: '["voting-worker","voting-result"]'
        creationTimestamp: null
        labels:
          app: postgresql
          app.kubernetes.io/component: database
          app.kubernetes.io/name: postgresql
          app.kubernetes.io/part-of: voting
          app.kubernetes.io/version: "1.0"
          deploymentconfig: postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: voting
          - name: POSTGRESQL_PASSWORD
            value: postgres
          - name: POSTGRESQL_USER
            value: postgres
          image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:10
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-volume-1
        volumes:
        - emptyDir: {}
          name: postgresql-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:10
          namespace: openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      app.openshift.io/connects-to: '["voting-worker","voting-result"]'
    creationTimestamp: null
    labels:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: voting
      app.kubernetes.io/version: "1.0"
    name: postgresql
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: voting
      app.kubernetes.io/version: "1.0"
      deploymentconfig: postgresql
  status:
    loadBalancer: {}
kind: List
metadata: {}
