apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-build
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
    params:
    - name: folder
      description: Path to build
      default: .
  outputs:
    resources:
    - name: workspace-git
      type: git
  steps:
  - name: build
    image: maven:3.6.0-jdk-8-slim
    command:
    - /usr/bin/mvn
    args:
    - --file=${inputs.params.folder}
    - dependency:resolve
    - verify
