apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: static-analysis
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
    params:
    - name: folder
      description: Path to build
      default: .
  steps:
    - name: pmd
      image: ubuntu
      command:
        - echo
      args:
        - "pmd"
    - name: sonar
      image: ubuntu
      command:
        - echo
      args:
        - "sonar"
