---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: kqr-build-pipeline
spec:
  resources:
  - name: samples-git
    type: git
  - name: qr-encode-image
    type: image
  - name: qr-decode-image
    type: image
  tasks:
  - name: build-qr-encode-image
    taskRef:
      name: s2i-buildah
    params:
    - name: contextFolder
      value: /workspace/qr-encode/
    - name: baseImage
      value: centos/python-36-centos7
    - name: verifyTLS
      value: "false"
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
      outputs:
      - name: image
        resource: qr-encode-image
  - name: build-qr-decode-image
    taskRef:
      name: buildah
    params:
    - name: contextFolder
      value: ./qr-decode/
    - name: verifyTLS
      value: "false"
    resources:
      inputs:
      - name: workspace-git
        resource: samples-git
      outputs:
      - name: image
        resource: qr-decode-image
