---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: "kqr-deploy-pipelinerun-"
spec:
  serviceAccount: pipeline
  pipelineRef:
    name: kqr-deploy-pipeline
  trigger:
    type: manual
  resources:
  - name: samples-git
    resourceRef:
      name: samples-git
  - name: qr-encode-image
    resourceRef:
      name: qr-encode-image
  - name: qr-decode-image
    resourceRef:
      name: qr-decode-image
