---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: samples-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/markito/kqr-pay
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: qr-encode-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-demo/qr-encode
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: qr-decode-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-demo/qr-decode
